$(document).ready(function () { $('.32_carousel').slick({ infinite: true, slidesToShow: 3, slidesToScroll: 1, responsive: [{ breakpoint: 1024, settings: { slidesToShow: 3, slidesToScroll: 3, infinite: true, dots: true } }, { breakpoint: 600, settings: { slidesToShow: 2, slidesToScroll: 2 } }, { breakpoint: 480, settings: { slidesToShow: 1, slidesToScroll: 1 } }] }); $('.dropdown-toggle').dropdown() }); $(window).load(function () { $(".twentytwenty-container[data-orientation!='vertical']").twentytwenty({ default_offset_pct: 0.7 }); $(".twentytwenty-container[data-orientation='vertical']").twentytwenty({ default_offset_pct: 0.3, orientation: 'vertical' }); }); document.addEventListener("DOMContentLoaded", function () { var div, n, v = document.getElementsByClassName("youtube-player"); for (n = 0; n < v.length; n++) { div = document.createElement("div"); div.setAttribute("data-id", v[n].dataset.id); div.innerHTML = labnolThumb(v[n].dataset.id); div.onclick = labnolIframe; v[n].appendChild(div); } }); function labnolThumb(id) { var thumb = '<img src="https://i.ytimg.com/vi/ID/hqdefault.jpg">', play = '<div class="play"></div>'; return thumb.replace("ID", id) + play; }
function labnolIframe() { var iframe = document.createElement("iframe"); var embed = "https://www.youtube.com/embed/ID?autoplay=1"; iframe.setAttribute("src", embed.replace("ID", this.dataset.id)); iframe.setAttribute("frameborder", "0"); iframe.setAttribute("allowfullscreen", "1"); this.parentNode.replaceChild(iframe, this); }
function myFunction() { var dots = document.getElementById("dots"); var moreText = document.getElementById("more"); var btnText = document.getElementById("myBtn"); if (dots.style.display === "none") { dots.style.display = "inline"; btnText.innerHTML = "Load more"; moreText.style.display = "none"; } else { dots.style.display = "none"; btnText.innerHTML = "Load less"; moreText.style.display = "inline"; } }
(function ($) {
    "use strict"; var cfg = { scrollDuration: 800, mailChimpURL: 'https://facebook.us8.list-manage.com/subscribe/post?u=cdb7b577e41181934ed6a6a44&amp;id=e6957d85dc' }, $WIN = $(window); var doc = document.documentElement; doc.setAttribute('data-useragent', navigator.userAgent); var ssPreloader = function () { $WIN.on('load', function () { $('html, body').animate({ scrollTop: 0 }, 'normal'); $("#preloader").delay(500).fadeOut('slow'); }); }; var ssMobileMenu = function () { var toggleButton = $('.header-menu-toggle'), nav = $('#header-nav-wrap'); toggleButton.on('click', function (event) { event.preventDefault(); toggleButton.toggleClass('is-clicked'); nav.slideToggle(); }); if (toggleButton.is(':visible')) nav.addClass('mobile'); $(window).resize(function () { if (toggleButton.is(':visible')) nav.addClass('mobile'); else nav.removeClass('mobile'); }); $('#header-nav-wrap').find('a').on("click", function () { if (nav.hasClass('mobile')) { toggleButton.toggleClass('is-clicked'); nav.slideToggle(); } }); }; var ssFitVids = function () { $(".fluid-video-wrapper").fitVids(); }; var ssOwlCarousel = function () { $(".owl-carousel").owlCarousel({ loop: true, nav: false, autoHeight: true, items: 1 }); }; var ssWaypoints = function () { var sections = $("section"), navigation_links = $(".vertical-nav li a"); sections.waypoint({ handler: function (direction) { var active_section; active_section = $('section#' + this.element.id); if (direction === "up") active_section = active_section.prev(); var active_link = $('.vertical-nav li a[href="#' + active_section.attr("id") + '"]'); navigation_links.parent().removeClass("current"); active_link.parent().addClass("current"); }, offset: '25%' }); }; var fixedNavigation = function () { $(window).scroll(function () { if ($(window).scrollTop() > 400) { $('#v-nav').css({ 'opacity': '1', 'display': 'block', 'transition': 'all ease 0.5s', 'webkit-transition': 'all ease 0.5s', }); } else { $('#v-nav').css({ 'opacity': '0', 'display': 'none', 'transition': 'all ease 0.5s', 'webkit-transition': 'all ease 0.5s', }); } }); }
    var ssSmoothScroll = function () { $('.smoothscroll').on('click', function (e) { var target = this.hash, $target = $(target); e.preventDefault(); e.stopPropagation(); $('html, body').stop().animate({ 'scrollTop': $target.offset().top }, cfg.scrollDuration, 'swing', function () { window.location.hash = target; }); }); }; var ssAlertBoxes = function () { $('.alert-box').on('click', '.close', function () { $(this).parent().fadeOut(500); }); }; var ssAOS = function () { AOS.init({ offset: 200, duration: 600, easing: 'ease-in-sine', delay: 300, once: true, disable: 'mobile' }); }; var ssAjaxChimp = function () { $('#mc-form').ajaxChimp({ language: 'es', url: cfg.mailChimpURL }); $.ajaxChimp.translations.es = { 'submit': 'Submitting...', 0: '<i class="fa fa-check"></i> We have sent you a confirmation email', 1: '<i class="fa fa-warning"></i> You must enter a valid e-mail address.', 2: '<i class="fa fa-warning"></i> E-mail address is not valid.', 3: '<i class="fa fa-warning"></i> E-mail address is not valid.', 4: '<i class="fa fa-warning"></i> E-mail address is not valid.', 5: '<i class="fa fa-warning"></i> E-mail address is not valid.' } }; var ssBackToTop = function () {
        var pxShow = 500, fadeInTime = 400, fadeOutTime = 400, scrollSpeed = 300, goTopButton = $("#go-top")
        $(window).on('scroll', function () { if ($(window).scrollTop() >= pxShow) { goTopButton.fadeIn(fadeInTime); } else { goTopButton.fadeOut(fadeOutTime); } });
    }; (function ssInit() { ssPreloader(); ssMobileMenu(); ssFitVids(); ssOwlCarousel(); ssWaypoints(); ssSmoothScroll(); ssPlaceholder(); ssAlertBoxes(); ssAOS(); ssBackToTop(); fixedNavigation(); })();
})(jQuery); $(document).ready(function () { $('.32_carousel').slick({ infinite: true, slidesToShow: 3, slidesToScroll: 1, responsive: [{ breakpoint: 1024, settings: { slidesToShow: 3, slidesToScroll: 3, infinite: true, dots: true } }, { breakpoint: 600, settings: { slidesToShow: 2, slidesToScroll: 2 } }, { breakpoint: 480, settings: { slidesToShow: 1, slidesToScroll: 1 } }] }); $(".regular ").slick({ dots: true, infinite: true, slidesToShow: 3, slidesToScroll: 3 }); }); $(window).load(function () { $(".twentytwenty-container[data-orientation!='vertical' ] ").twentytwenty({ default_offset_pct: 0.7 }); $(".twentytwenty-container[data-orientation='vertical' ] ").twentytwenty({ default_offset_pct: 0.3, orientation: 'vertical' }); }); function checkmail() {
    var name = document.getElementById("fullname").value; var location = document.getElementById("mobile").value; var address = document.getElementById("address").value; if (name != "" && location != "" && address != "") {
        var xmlhttp = new XMLHttpRequest(); xmlhttp.onreadystatechange = function () { if (this.readyState == 4 && this.status == 200) { document.getElementById("vinayak").innerHTML = this.responseText; document.getElementById("vinayak2").style.display = "none"; } }
        xmlhttp.open("GET", "gethint1.php?name=" + name + "&mobile=" + location + "&address=" + address, true); xmlhttp.send();
    }
}
function myFunction() { var dots = document.getElementById("dots "); var moreText = document.getElementById("more "); var btnText = document.getElementById("myBtn "); if (dots.style.display === "none ") { dots.style.display = "inline "; btnText.innerHTML = "Load more "; moreText.style.display = "none "; } else { dots.style.display = "none "; btnText.innerHTML = "Load less "; moreText.style.display = "inline "; } }



